language: node_js
node_js:
- '9'
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: build
  skip_cleanup: true
  bucket: marketplace-client
  region: eu-central-1
script: 
    - npm run build