version: '3.5'

services:
  marketplace-frontend:
    container_name: marketplace-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
  identities-service:
    image: identities-service:latest
    build: ~/repo/identities-service/
    ports:
      - '9091:9090'
    environment:
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=identities