version: '3.5'

services:
  marketplace-frontend:
    container_name: marketplace-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
  identity-service:
    image: identity-service:latest
    build: ~/repo/identities-service/
    ports:
      - '5000'